
services:
  downloader:
    build: .
    container_name: zoom-earth-downloader
    restart: unless-stopped
    
    volumes:
      - "${HOST_DATA_PATH}:/data/tiles"
    env_file:
      - .env.production
      
    environment:
      - TZ=Asia/Shanghai
      - DOWNLOAD_PATH=/data/tiles