
services:
  downloader:
    build: .
    container_name: zoom-earth-downloader
    restart: unless-stopped
    
    volumes:
      - "${HOST_DATA_PATH}:/data/tiles"
    # ----------------- 关键修改部分结束 -----------------
      
    # (可选) 挂载 .env 文件，方便在不重建镜像的情况下修改配置
    # 注意：Docker Compose v2.20+ 默认就会加载 .env 文件，
    # 所以这行不是严格必需的，但保留它可以增强可读性。
    env_file:
      - .env.production
      
    # 确保容器内的脚本也使用 /data/tiles 作为下载路径
    environment:
      - DOWNLOAD_PATH=/data/tiles